spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: username
    password: password
    type: org.apache.tomcat.jdbc.pool.DataSource

    #connection pool properties
    tomcat:
      initial-size: 1
      max-active: 5
      max-idle: 2
      min-idle: 1


#generation properties
certificate:
  amount: 10
  name:
    minSize: 3
    maxSize: 50
  description:
    minSize: 150
    maxSize: 3000
  price:
    min: 100
    max: 1000
  duration:
    min: 3
    max: 31
  tag-amount:
    min: 3
    max: 10

tag:
  amount: 10
  name:
    minSize: 3
    maxSize: 25

user:
  amount: 10
  first-name:
    minSize: 3
    maxSize: 25
  last-name:
    minSize: 3
    maxSize: 25
  login:
    minSize: 3
    maxSize: 25
  password:
    minSize: 3
    maxSize: 25

user-order:
  amount: 10

generator:
  dictionary-file: data-generation/src/main/resources/dictionary.txt