spring:

  #jpa properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  #datasource properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databaseName
    username: username
    password: password
    type: org.apache.tomcat.jdbc.pool.DataSource

    #connection pool properties
    tomcat:
      initial-size: 1
      max-active: 5
      max-idle: 2
      min-idle: 1